country_emoji_map = {
    "United States": "🇺🇸",
    "Germany": "🇩🇪",
    "United Kingdom": "🇬🇧",
    "France": "🇫🇷",
    "Switzerland": "🇨🇭",
    "Canada": "🇨🇦",
    "Japan": "🇯🇵",
    "Republic of Korea": "🇰🇷",
    "Singapore": "🇸🇬",
    "United Arab Emirates": "🇦🇪",
    "El Salvador": "🇸🇻",
    "China": "🇨🇳",
    "Sweden": "🇸🇪",
    "Netherlands": "🇳🇱",
    "Norway": "🇳🇴",
    "Denmark": "🇩🇰",
    "Finland": "🇫🇮",
    "Spain": "🇪🇸",
    "Italy": "🇮🇹",
    "Portugal": "🇵🇹",
    "Ireland": "🇮🇪",
    "Austria": "🇦🇹",
    "Luxembourg": "🇱🇺",
    "Belgium": "🇧🇪",
    "Poland": "🇵🇱",
    "Czechia": "🇨🇿",
    "Hungary": "🇭🇺",
    "Romania": "🇷🇴",
    "Turkey": "🇹🇷",
    "Israel": "🇮🇱",
    "India": "🇮🇳",
    "Australia": "🇦🇺",
    "New Zealand": "🇳🇿",
    "Brazil": "🇧🇷",
    "Argentina": "🇦🇷",
    "Mexico": "🇲🇽",
    "South Africa": "🇿🇦",
    "Nigeria": "🇳🇬",
    "Hong Kong": "🇭🇰",
    "Taiwan": "🇹🇼",
    "Thailand": "🇹🇭",
    "Vietnam": "🇻🇳",
    "Philippines": "🇵🇭",
    "Indonesia": "🇮🇩",
    "Saudi Arabia": "🇸🇦",
    "Qatar": "🇶🇦",
    "Kuwait": "🇰🇼",
    "Cyprus": "🇨🇾",
    "Malta": "🇲🇹",
    "Iceland": "🇮🇸",
    "Estonia": "🇪🇪",
    "Lithuania": "🇱🇹",
    "Latvia": "🇱🇻",
    "Ukraine": "🇺🇦",
    "Bhutan": "🇧🇹",
    "North Korea": "🇰🇵",
    "Cayman Islands": "🇰🇾",
    "British Virgin Islands": "🇻🇬",
    "Venezuela": "🇻🇪",
    "Decentralized": "🌐",
    "Gibraltar": "🇬🇮",
    "Bermuda": "🇧🇲",
    "Liberia": "🇱🇷",
    "Panama": "🇵🇦",
    "Bahrain": "🇧🇭",
    "Jersey": "🇯🇪",
    "Malaysia": "🇲🇾",
    "Other": "🏳️",
}