name: crypto-treasury-env
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas
  - pip
  - pip:
      - streamlit
      - gspread
      - oauth2client
      - plotly
      - altair
      - posthog>=3.5.1,<4
      - extra-streamlit-components>=0.1.71
